version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  build-and-test:
    executor:
      name: python/default
      tag: "3.6"

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install libcurl4-openssl-dev
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Test
          command: |
            mkdir test-results
            python -m pytest --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  main:
    jobs:
      - build-and-test

